### ISSUE TITLE
TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'

### ISSUE THREAD

**Issue by ninjaguardian** [tensorforce/tensorforce#905]
I believe i found the issue. Installing tensorforce installs h5py 3.1.0. That installs numpy 1.9.3 and doesn't work with python 3.11. h5py 3.10.0 worked, but tensorflow wont let me use that.

**Comment by ninjaguardian** [comment]
If this is unfixable, do you know what python versions do work?

**Comment by JesusmiCaH** [comment]
Based on my experience, it successfully works on Python 3.9. 😄
